FROM debian
RUN apt-get update
RUN apt-get install maven -y
RUN apt-get install openjdk-11-jdk -y
COPY user-0.0.1-SNAPSHOT.jar /opt/
CMD java -jar /opt/user-0.0.1-SNAPSHOT.jar
EXPOSE  8082/tcp
EXPOSE  3306/tcp