FROM debian


RUN apt-get update
RUN apt-get install maven -y
RUN apt-get install openjdk-11-jdk -y
COPY eureka-server-0.0.1-SNAPSHOT.jar /opt/

CMD java -jar /opt/eureka-server-0.0.1-SNAPSHOT.jar
EXPOSE  8761/tcp